apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-crud-api-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /var/lib/postgresql/data


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-crud-api-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
